require('basic')
require("keybindings")
require("plugins")
require("colorscheme")
require("plugin-config.nvim-tree")
require("plugin-config.barbar")
require("plugin-config.lualine")
require("plugin-config.nvim-treesitter")
require("lsp.setup")
require("lsp.cmp")
require("plugin-config.dashboard")
require("plugin-config.project")
require("plugin-config.lsp-signature")
require("plugin-config.auto-pairs")
require("plugin-config.code-runner")
require("plugin-config.leap")
require("plugin-config.comment")
-- require('plugin-config.vscode')
